#ifndef __SCENE_GRAPH_GANTRY_APPEARANCE_TYPE_H
#define __SCENE_GRAPH_GANTRY_APPEARANCE_TYPE_H

enum gantry_appearance_type {
	GANTRY_APPEARANCE_NO_LIGHTS,
	GANTRY_APPEARANCE_FIRST_LIGHT,
	GANTRY_APPEARANCE_SECOND_LIGHT,
	GANTRY_APPEARANCE_THIRD_LIGHT,
	GANTRY_APPEARANCE_FOURTH_LIGHT,
};

#endif
